name: SRComp Validate Action
description: A GitHub Action to validate a compstate.
runs:
  using: composite
  steps:
    - name: Copy requirements locally
      id: copy-requirements
      shell: bash
      run: |
        # `cache-dependency-path` seems to need to be within the current directory. Use a temporary directory
        #
        tempdir=$(mktemp --directory --tmpdir=. --suffix=-srcomp-validate-action)
        cp ${{ github.action_path }}/**requirements.txt $tempdir
        echo "directory=${tempdir}" >> $GITHUB_OUTPUT

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: pip
        cache-dependency-path: ${{ steps.copy-requirements.outputs.directory }}/**requirements.txt

    - name: Install Dependencies
      shell: bash
      run: pip install -U -r ${{ steps.copy-requirements.outputs.directory }}/requirements.txt

    - name: Run Scoring tests
      shell: bash
      run: |
        python3 -m unittest discover --buffer scoring/

        if [ -d scoring/tests/ ]
        then
          python3 -m unittest discover --buffer scoring/tests/
        fi

    - name: Run Compstate Validation
      shell: bash
      run: ${{ github.action_path }}/validate.py .
