name: SRComp Validate Action
description: A GitHub Action to validate a compstate.
runs:
  using: composite
  steps:
    - name: Copy requirements locally
      id: copy-requirements
      shell: bash
      run: |
        # `cache-dependency-path` seems to need to be within the current directory. Use a temporary directory
        #
        tempdir=$(mktemp --directory --tmpdir=. --suffix=-srcomp-validate-action)
        cp ${{ github.action_path }}/**requirements.txt $tempdir
        echo "directory=${tempdir}" >> $GITHUB_OUTPUT

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.14'
        cache: pip
        cache-dependency-path: ${{ steps.copy-requirements.outputs.directory }}/**requirements.txt

    - name: Install Dependencies
      shell: bash
      run: pip install -U -r ${{ steps.copy-requirements.outputs.directory }}/requirements.txt

    - name: Run Scoring tests
      shell: bash
      run: |
        # Do our own error handling as unittest discover exits with code 5 to
        # mean "no tests found", which is fine.
        set +e
        python3 -m unittest discover --buffer scoring/
        result=$?
        set -x
        if [ "$result" -ne 0 ] && [ "$result" -ne 5 ]
        then
          exit $result
        fi

        if [ -d scoring/tests/ ]
        then
          set +e
          python3 -m unittest discover --buffer scoring/tests/
          set -x
          result=$?
          if [ "$result" -ne 0 ] && [ "$result" -ne 5 ]
          then
            exit $result
          fi
        fi

    - name: Run Compstate Validation
      shell: bash
      run: ${{ github.action_path }}/validate.py .
